package com.xce.jam;

import io.reactivex.annotations.SchedulerSupport;

/* JADX INFO: loaded from: classes.dex */
public class JAMRes_en extends JAMRes {
    public JAMRes_en() {
        this.INFO_NAME = "<Name>";
        this.INFO_VENDOR = "<Vendor>";
        this.INFO_SIZE = "<Size>";
        this.INFO_EXPIRED = "<Exp-Date>";
        this.INFO_UNLIMITED = "Unlimited";
        this.INFO_CATEGORY = "<Category>";
        this.INFO_NONE = SchedulerSupport.NONE;
        this.INFO_YEAR = "Year";
        this.INFO_MONTH = "Month";
        this.INFO_DAY = "Day";
        this.INFO_HOUR = "Hour";
        this.INFO_MIN = "Minute";
        this.MSG_FAIL_CONN = "Connection Error. Try Again.";
        this.MSG_LACK_PROP = "Attribute Error. MSD File Error.";
        this.MSG_NOT_DATA = "Data Error, Try Again";
        this.MSG_DEL = "Do you want to delete this application?";
        this.MSG_NOT_READ = "Can't read.";
        this.MSG_NOT_CREATE = "Can't create.";
        this.MSG_UNKNOWN = "Unkown Error, Contact the Service Provider";
        this.MSG_CONN = "Connect to WAP to download a new one.";
        this.MSG_CHAT = "Chatting keyword";
        this.MSG_DELING = "Deleting";
        this.MSG_SEARCHING = "Searching";
        this.MSG_SAVING = "Saving";
        this.MSG_NOT_WRITE = "Can't write a file";
        this.MSG_EXPIRED = "Expired!!";
        this.MSG_UPDATE = "Do you want to upgrade this program to a new version?";
        this.ABOUT_UPGRADE = "Do you want to upgrade it to a new one?";
        this.ABOUT_UPDATE = "Do you want to update the expiration date?";
        this.ABOUT_UNEXPIRED = "The same program already exists.";
        this.ABOUT_PLATFORM = "Upgrade the platform.";
        this.ABOUT_PROFILE = "Error in MicroEdition-Profile Attribute.";
        this.ABOUT_CONTENTS = "Content Name";
        this.ABOUT_JAR_SIZE = "Error in MIDlet-Jar-Size Attribute.";
        this.ABOUT_SIZE = "Size";
        this.ABOUT_DOWNLOAD = "Do you want to download the program?";
        this.ABOUT_XDATE = "Error in MIDlet-X-Date Attribute";
        this.ABOUT_EXPIRATION = "Expiration Date";
        this.COMPLETE_RUN = "Downloading completed. Do you want to run it right now?";
        this.DELETE_LACK = "Insufficient space";
        this.DELETE_DELETE = "You are charged for downloading this program again to use. Do you really want to delete it?";
        this.DELETE_EXPIRED = "programs are expired. Do you want to delete all of them?";
        this.DOWNLOAD_SPACE = "Insufficient space.";
        this.DOWNLOAD_RETRY = "Download aborted. Do you want to try agin?";
        this.DOWNLOAD_ERR = "Unknown Error occurred. Contact the service provider.";
        this.DOWNLOAD_MSD = "Info";
        this.DOWNLOAD_ICON = "Resource";
        this.DOWNLOAD_JAR = "Contents";
        this.MAIN_NOT_DEL = "Can't delete the item.";
        this.MAIN_NOT_ALLDEL = "No item to delete";
        this.MAIN_NOT_PROP = "Can't find the information on the item.";
        this.SYS_MEMORY = "*Free Space:";
        this.SYS_COUNT = "*Num of contents:";
        this.SYS_ICON = "*View:Icon";
        this.SYS_LIST = "*View:List";
        this.SYS_SORT_DOWN = "*Sort:Download";
        this.SYS_SORT_COUNT = "*Sort:Frequency";
        this.SYS_SORT_TIME = "*Sort:Latest Use";
        this.SYS_SORT_USER = "*Sort:Custom";
        this.SYS_SOUND = "*Sound:";
        this.CONTENTS_EMPTY = "Download for use";
        this.SORT_TOP = "Do you want to put this program to the top of the list?";
        this.SORT_USER = "Sort Type is changed to User Customization Type.";
        this.MENU_APP = "MENU";
        this.MENU_OPTION = "OPTION";
        this.MENU_SELECT_VIEW = "View";
        this.MENU_SET_VOLUME = "Volume";
        this.MENU_SORT_ALL = "Sort";
        this.MENU_DELETE = "Delete";
        this.MENU_SYSTEM_INFO = "System Info";
        this.MENU_APP_INFO = "Info";
        this.MENU_APP_SORT = "Sort";
        this.MENU_APP_UPGRADE = "Upgrade";
        this.MENU_VIEW_LIST = "List-View";
        this.MENU_VIEW_ICON = "Icon-View";
        this.MENU_NATE_SITE = "WAP";
        this.MENU_SORT_DOWN = "Download";
        this.MENU_SORT_TIME = "Latest Use";
        this.MENU_SORT_COUNT = "Frequency";
        this.MENU_DELETE_ALL = "All";
        this.MENU_DELETE_EXP = "Expired";
        this.MENU_SORT_TOP = "To the top";
        this.MENU_SORT_USER = "Custom";
        this.MENU_SORT_UPDOWN = "Up / Down";
        this.MENU_GVM_CHAT = "Chatting keyword";
    }
}
